name: Keep n8n Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Allows you to run it manually if needed

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render n8n URL
        run: curl -s https://n8n-p42r.onrender.com || echo "Ping failed"
